name: scheduled-test
on:
    schedule:
        - cron: '5 5 * * *'
jobs:
    alert:
        runs-on: ubuntu-latest
        steps:
            - name: print message
              run: echo "This is a scheduled test"
